Error: Failure in `/tmp/RtmptKCFyF/R_LIBS296595100f3/packager/packager-tests/runit.Rout.fail`
> #!/usr/bin/Rscript --vanilla
> is_failure <- function(result) {
+     res <- result[[1]]
+     names(res) <- tolower(names(res)) # soothe lintr
+     sum_of_exceptions <- res[["nerr"]] + res[["nfail"]]
+     fail <- as.logical(sum_of_exceptions)
+     return(fail)
+ }
> unit_dir <- system.file("tests", "runit", package = "packager")
> if (unit_dir == "") {
+     devtools::load_all(pkg = ".") # needed to use devtools' shim version of 
+     # base::system.file()
+     unit_dir <- system.file("tests", "runit", package = "packager")
+ }
> package_suite <- RUnit::defineTestSuite("packager_unit_test",
+                                         dirs = unit_dir,
+                                         testFileRegexp = "^.*\\.[rR]",
+                                         testFuncRegexp = "^test_+")
> test_result <- RUnit::runTestSuite(package_suite)


Executing test function test_exception  ...
Execution halted
