RUNIT TEST PROTOCOL -- Tue Feb  6 20:57:44 2018 
*********************************************** 
Number of test functions: 17 
Number of errors: 0 
Number of failures: 1 

 
1 Test Suite : 
packager_unit_test - 17 test functions, 0 errors, 1 failure
FAILURE in test_travis: Error in RUnit::checkException(packager:::travis_cli(path)) : 
  Error not generated as expected




Details 
*************************** 
Test Suite: packager_unit_test 
Test function regexp: ^test_+ 
Test file regexp: ^test.*\.[rR] 
Involved directory: 
inst/runit_tests 
--------------------------- 
Test file: inst/runit_tests/test_devtools_modified.R 
test_union_write: (2 checks) ... OK (0 seconds)
test_use_git: (2 checks) ... OK (0.15 seconds)
test_use_git_ignore: (2 checks) ... OK (0 seconds)
--------------------------- 
Test file: inst/runit_tests/test_internal.R 
test_get_news: (1 checks) ... OK (0.65 seconds)
test_git: (5 checks) ... OK (0.07 seconds)
test_grep_directory: (1 checks) ... OK (0 seconds)
test_is_force: (1 checks) ... OK (0 seconds)
test_is_null_or_true: (3 checks) ... OK (0 seconds)
test_travis: FAILURE !! (check number 1)
Error in RUnit::checkException(packager:::travis_cli(path)) : 
  Error not generated as expected

test_url: (8 checks) ... OK (0.01 seconds)
test_warn_and_stop: (1 checks) ... OK (0 seconds)
--------------------------- 
Test file: inst/runit_tests/test_throw.R 
test_exception: (1 checks) ... OK (0 seconds)
--------------------------- 
Test file: inst/runit_tests/test_tools.R 
test_add_commit: (3 checks) ... OK (0.01 seconds)
test_cran_comments: (1 checks) ... OK (0.12 seconds)
test_githuburl: (4 checks) ... OK (1.55 seconds)
test_git_tag: (7 checks) ... OK (0.12 seconds)
test_news: (5 checks) ... OK (1.57 seconds)
