

Executing test function test_union_write  ...  done successfully.



Executing test function test_use_git  ... * Initialising repo
* Adding `.Rproj.user`, `.Rhistory`, `.RData` to /tmp/RtmpebeF1a/fakePackge/.gitignore
* Adding files and committing
* Git is already initialized
 done successfully.



Executing test function test_use_git_ignore  ... * Adding `foo`, `bar` to /tmp/RtmpebeF1a/fakePackge/.gitignore
 done successfully.



Executing test function test_get_news  ... * Creating `NEWS.md` from template.
* Modify `NEWS.md`.
 done successfully.



Executing test function test_git  ... Error in .local(path, ...) : The 'path' is not in a git repository
* Initialising repo
* Adding `.Rproj.user`, `.Rhistory`, `.RData` to /tmp/RtmpebeF1a/file3f387b9de300/fakePackage/.gitignore
* Adding files and committing
 done successfully.



Executing test function test_grep_directory  ...  done successfully.



Executing test function test_is_force  ...  done successfully.



Executing test function test_is_null_or_true  ...  done successfully.



Executing test function test_travis  ... SSL error: could not verify peer
Error in (k + 1):(k + 3) : argument of length 0
In addition: Warning message:
In system2("sudo", paste("travis logs --repo", travis_repo), stdout = TRUE) :
  running command ''sudo' travis logs --repo fvafrCU/packager' had status 1
 done successfully.



Executing test function test_url  ... Error in packager:::get_github_url(url, return_only_one = TRUE, force = FALSE) : 
  Found multiple github URL.
In addition: Warning message:
In packager:::get_github_url(url, return_only_one = TRUE) :
  Found multiple github URL, using the first.
 done successfully.



Executing test function test_warn_and_stop  ... fooError in packager:::warn_and_stop("foo") : foo
 done successfully.



Executing test function test_exception  ... Error in eval(expr, envir = parent.frame()) : Hello, error!
 done successfully.



Executing test function test_add_commit  ... Error in git2r::commit(repository, commit_message) : 
  Error in 'git2r_commit': Nothing added to commit

In addition: Warning message:
In value[[3L]](cond) : Nothing added.
 done successfully.



Executing test function test_cran_comments  ...  done successfully.



Executing test function test_git_tag  ... Creating package 'fake' in '/tmp/RtmpebeF1a'
No DESCRIPTION found. Creating with values:


Package: fake
Title: What the Package Does (one line, title case)
Version: 0.0.0.9000
Authors@R: person("First", "Last", email = "first.last@example.com", role = c("aut", "cre"))
Description: What the package does (one paragraph).
Depends: R (>= 3.5.0)
License: What license is it under?
Encoding: UTF-8
LazyData: true
* Creating `fake.Rproj` from template.
* Adding `.Rproj.user`, `.Rhistory`, `.RData` to ./.gitignore
Not a git repository.Error in warn_and_stop("Not a git repository.") : Not a git repository.
* Initialising repo
* Adding `.Rproj.user`, `.Rhistory`, `.RData` to /tmp/RtmpebeF1a/fake/.gitignore
* Adding files and committing
Package version bumped from ‘0.0.0.9000’ to ‘0.1.0’
Uncommited changes, aborting.Error in warn_and_stop("Uncommited changes, aborting.") : 
  Uncommited changes, aborting.
File DESCRIPTION has version 0.0.3, but I found 0.1.0 in the git repository's tags.Error in warn_and_stop(paste0("File DESCRIPTION has version ", version,  : 
  File DESCRIPTION has version 0.0.3, but I found 0.1.0 in the git repository's tags.
 done successfully.



Executing test function test_githuburl  ... Creating package 'fake' in '/tmp/RtmpebeF1a'
No DESCRIPTION found. Creating with values:


Package: fake
Title: What the Package Does (one line, title case)
Version: 0.0.0.9000
Authors@R: person("First", "Last", email = "first.last@example.com", role = c("aut", "cre"))
Description: What the package does (one paragraph).
Depends: R (>= 3.5.0)
License: What license is it under?
Encoding: UTF-8
LazyData: true
* Creating `fake.Rproj` from template.
* Adding `.Rproj.user`, `.Rhistory`, `.RData` to ./.gitignore
Creating package 'fake' in '/tmp/RtmpebeF1a'
No DESCRIPTION found. Creating with values:


Package: fake
Title: What the Package Does (one line, title case)
Version: 0.0.0.9000
Authors@R: person("First", "Last", email = "first.last@example.com", role = c("aut", "cre"))
Description: What the package does (one paragraph).
Depends: R (>= 3.5.0)
License: What license is it under?
Encoding: UTF-8
LazyData: true
* Creating `fake.Rproj` from template.
* Adding `.Rproj.user`, `.Rhistory`, `.RData` to ./.gitignore
 done successfully.



Executing test function test_news  ... Creating package 'fakePackge' in '/tmp/RtmpebeF1a'
No DESCRIPTION found. Creating with values:


Package: fakePackge
Title: What the Package Does (one line, title case)
Version: 0.0.0.9000
Authors@R: person("First", "Last", email = "first.last@example.com", role = c("aut", "cre"))
Description: What the package does (one paragraph).
Depends: R (>= 3.5.0)
License: What license is it under?
Encoding: UTF-8
LazyData: true
Timing stopped at: 0.008 0.004 0.022
Error : deps must be a data frame with character columns ‘type’, ‘package’, ‘version’
In addition: Warning messages:
1: In add_github_url_to_desc(path = path) :
  Could not retrieve github user name. Set the URL in DESCRIPTION manually!
2: In add_github_url_to_desc(path = path, default_gh_user = NA) :
  Found 0 git remotes refering to `fake`.
3: In add_github_url_to_desc(path = path, default_gh_user = NA) :
  Could not retrieve github user name. Set the URL in DESCRIPTION manually!
 done successfully.

Number of test functions: 17 
Number of errors: 1 
Number of failures: 0 
Error: RUnit failed. 
Execution halted
